#!/bin/bash

# this script uses netcat to send commands over UDP to a running audio_thingy server

Help()
{
  echo "a script for controlling an audio_thingy server via UDP"
  echo "note: requires netcat"
  echo
  echo "-h	show help"
  echo "-p	set port"
  echo "-r	reloads client"
  echo "-q	quits server"
  echo "-s	set IP address"
  echo "-f	set filename of sketch"
  echo
}

SERVER="127.0.0.1"
PORT=2000
MESSAGE=""

while getopts "hrqp:s:f:" option; do
  case $option in
    s) SERVER="$OPTARG"
      ;;
    r) MESSAGE="reload"
      ;;
    q) MESSAGE="quit"
      ;;
    p) PORT="$OPTARG"
      ;;
    f) MESSAGE="sketch $OPTARG"
      ;;
    h) Help
      exit;;
  esac
done

if [[ $MESSAGE == "" ]]; then
  echo "[ERROR] needs at least one message flag"
  exit
fi

echo "sending \"$MESSAGE\" to $SERVER:$PORT"
echo $MESSAGE | nc --udp --close $SERVER $PORT
